export const ALL_GUEST_REQUEST = "ALL_GUEST_REQUEST";
export const ALL_GUEST_SUCCESS = "ALL_GUEST_SUCCESS";
export const ALL_GUEST_FAIL = "ALL_GUEST_FAIL";

export const ADMIN_GUEST_REQUEST = "ADMIN_GUEST_REQUEST";
export const ADMIN_GUEST_SUCCESS = "ADMIN_GUEST_SUCCESS";
export const ADMIN_GUEST_FAIL = "ADMIN_GUEST_FAIL";

export const NEW_GUEST_REQUEST = "NEW_GUEST_REQUEST";
export const NEW_GUEST_SUCCESS = "NEW_GUEST_SUCCESS";
export const NEW_GUEST_RESET = "NEW_GUEST_RESET";
export const NEW_GUEST_FAIL = "NEW_GUEST_FAIL";

export const UPDATE_GUEST_REQUEST = "UPDATE_GUEST_REQUEST";
export const UPDATE_GUEST_SUCCESS = "UPDATE_GUEST_SUCCESS";
export const UPDATE_GUEST_RESET = "UPDATE_GUEST_RESET";
export const UPDATE_GUEST_FAIL = "UPDATE_GUEST_FAIL";

export const DELETE_GUEST_REQUEST = "DELETE_GUEST_REQUEST";
export const DELETE_GUEST_SUCCESS = "DELETE_GUEST_SUCCESS";
export const DELETE_GUEST_RESET = "DELETE_GUEST_RESET";
export const DELETE_GUEST_FAIL = "DELETE_GUEST_FAIL";

export const GUEST_DETAILS_REQUEST = "GUEST_DETAILS_REQUEST";
export const GUEST_DETAILS_SUCCESS = "GUEST_DETAILS_SUCCESS";
export const GUEST_DETAILS_FAIL = "GUEST_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";