export const CREATE_PARTICIPATION_REQUEST = "CREATE_PARTICIPATION_REQUEST";
export const CREATE_PARTICIPATION_SUCCESS = "CREATE_PARTICIPATION_SUCCESS";
export const CREATE_PARTICIPATION_FAIL = "CREATE_PARTICIPATION_FAIL";

export const MY_PARTICIPATIONS_REQUEST = "MY_PARTICIPATIONS_REQUEST";
export const MY_PARTICIPATIONS_SUCCESS = "MY_PARTICIPATIONS_SUCCESS";
export const MY_PARTICIPATIONS_FAIL = "MY_PARTICIPATIONS_FAIL";

export const ALL_PARTICIPATIONS_REQUEST = "ALL_PARTICIPATIONS_REQUEST";
export const ALL_PARTICIPATIONS_SUCCESS = "ALL_PARTICIPATIONS_SUCCESS";
export const ALL_PARTICIPATIONS_FAIL = "ALL_PARTICIPATIONS_FAIL";

export const DELETE_PARTICIPATION_REQUEST = "DELETE_PARTICIPATION_REQUEST";
export const DELETE_PARTICIPATION_SUCCESS = "DELETE_PARTICIPATION_SUCCESS";
export const DELETE_PARTICIPATION_RESET = "DELETE_PARTICIPATION_RESET";
export const DELETE_PARTICIPATION_FAIL = "DELETE_PARTICIPATION_FAIL";

export const  PARTICIPATION_DETAILS_REQUEST = " PARTICIPATION_DETAILS_REQUEST";
export const  PARTICIPATION_DETAILS_SUCCESS = " PARTICIPATION_DETAILS_SUCCESS";
export const  PARTICIPATION_DETAILS_FAIL = " PARTICIPATION_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";