export const ALL_SPONSOR_REQUEST = "ALL_SPONSOR_REQUEST";
export const ALL_SPONSOR_SUCCESS = "ALL_SPONSOR_SUCCESS";
export const ALL_SPONSOR_FAIL = "ALL_SPONSOR_FAIL";

export const ADMIN_SPONSOR_REQUEST = "ADMIN_SPONSOR_REQUEST";
export const ADMIN_SPONSOR_SUCCESS = "ADMIN_SPONSOR_SUCCESS";
export const ADMIN_SPONSOR_FAIL = "ADMIN_SPONSOR_FAIL";

export const NEW_SPONSOR_REQUEST = "NEW_SPONSOR_REQUEST";
export const NEW_SPONSOR_SUCCESS = "NEW_SPONSOR_SUCCESS";
export const NEW_SPONSOR_RESET = "NEW_SPONSOR_RESET";
export const NEW_SPONSOR_FAIL = "NEW_SPONSOR_FAIL";

export const UPDATE_SPONSOR_REQUEST = "UPDATE_SPONSOR_REQUEST";
export const UPDATE_SPONSOR_SUCCESS = "UPDATE_SPONSOR_SUCCESS";
export const UPDATE_SPONSOR_RESET = "UPDATE_SPONSOR_RESET";
export const UPDATE_SPONSOR_FAIL = "UPDATE_SPONSOR_FAIL";

export const DELETE_SPONSOR_REQUEST = "DELETE_SPONSOR_REQUEST";
export const DELETE_SPONSOR_SUCCESS = "DELETE_SPONSOR_SUCCESS";
export const DELETE_SPONSOR_RESET = "DELETE_SPONSOR_RESET";
export const DELETE_SPONSOR_FAIL = "DELETE_SPONSOR_FAIL";

export const SPONSOR_DETAILS_REQUEST = "SPONSOR_DETAILS_REQUEST";
export const SPONSOR_DETAILS_SUCCESS = "SPONSOR_DETAILS_SUCCESS";
export const SPONSOR_DETAILS_RESET = "SPONSOR_DETAILS_RESET";
export const SPONSOR_DETAILS_FAIL = "SPONSOR_DETAILS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";