export const ALL_TEAM_REQUEST = "ALL_TEAM_REQUEST";
export const ALL_TEAM_SUCCESS = "ALL_TEAM_SUCCESS";
export const ALL_TEAM_FAIL = "ALL_TEAM_FAIL";

export const ADMIN_TEAM_REQUEST = "ADMIN_TEAM_REQUEST";
export const ADMIN_TEAM_SUCCESS = "ADMIN_TEAM_SUCCESS";
export const ADMIN_TEAM_FAIL = "ADMIN_TEAM_FAIL";

export const NEW_TEAM_REQUEST = "NEW_TEAM_REQUEST";
export const NEW_TEAM_SUCCESS = "NEW_TEAM_SUCCESS";
export const NEW_TEAM_RESET = "NEW_TEAM_RESET";
export const NEW_TEAM_FAIL = "NEW_TEAM_FAIL";

export const UPDATE_TEAM_REQUEST = "UPDATE_TEAM_REQUEST";
export const UPDATE_TEAM_SUCCESS = "UPDATE_TEAM_SUCCESS";
export const UPDATE_TEAM_RESET = "UPDATE_TEAM_RESET";
export const UPDATE_TEAM_FAIL = "UPDATE_TEAM_FAIL";

export const DELETE_TEAM_REQUEST = "DELETE_TEAM_REQUEST";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_RESET = "DELETE_TEAM_RESET";
export const DELETE_TEAM_FAIL = "DELETE_TEAM_FAIL";

export const TEAM_DETAILS_REQUEST = "TEAM_DETAILS_REQUEST";
export const TEAM_DETAILS_SUCCESS = "TEAM_DETAILS_SUCCESS";
export const TEAM_DETAILS_FAIL = "TEAM_DETAILS_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";